name: Append daily history (ASTRA4)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"   # 毎日 10:15 JST（引け後の安全帯）

permissions:
  contents: write

concurrency:
  group: astra4-append-${{ github.ref }}
  cancel-in-progress: false

jobs:
  append:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      INDEX_KEY: astra4
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas; fi

      - name: Append one row to history
        run: |
          python scripts/append_history.py
          date -u +"%Y-%m-%dT%H:%M:%SZ" > "$OUT_DIR/_last_run.txt"
          tail -n 5 "$OUT_DIR/${INDEX_KEY}_history.csv" || true
          ls -lah "$OUT_DIR" || true

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_DIR/${INDEX_KEY}_history.csv" "$OUT_DIR/_last_run.txt" 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(astra4): append daily history"
            git push
          fi
