name: ASTRA4 • intraday snapshot (JST)

on:
  workflow_dispatch:
    inputs:
      session_start:
        description: "Session start (HH:MM JST)"
        required: true
        default: "09:00"
      session_end:
        description: "Session end (HH:MM JST)"
        required: true
        default: "15:30"
      day_anchor:
        description: "Day anchor time for labeling (HH:MM JST)"
        required: true
        default: "09:00"
      basis:
        description: "Return basis label"
        required: true
        default: "prev_close"
      value_type:
        description: "値の種類 (ratio=倍率, percent=%)"
        required: true
        default: "ratio"

permissions:
  contents: write

concurrency:
  group: astra4-intraday-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify scripts & inputs exist
        run: |
          test -f scripts/make_intraday_post.py || (echo "Missing scripts/make_intraday_post.py" && exit 2)
          test -f docs/outputs/astra4_intraday.csv || (echo "Missing docs/outputs/astra4_intraday.csv" && exit 2)
          [[ "${{ inputs.session_start }}" =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "session_start invalid"; exit 2)
          [[ "${{ inputs.session_end }}"   =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "session_end invalid";   exit 2)
          [[ "${{ inputs.day_anchor }}"    =~ ^[0-9]{2}:[0-9]{2}$ ]] || (echo "day_anchor invalid";    exit 2)

      - name: Generate intraday post and snapshot
        env:
          INDEX_KEY: astra4
          CSV: docs/outputs/astra4_intraday.csv
          OUT_JSON: docs/outputs/astra4_stats.json
          OUT_TEXT: docs/outputs/astra4_post_intraday.txt
          SNAPSHOT_PNG: docs/outputs/astra4_intraday.png
          SESSION_START: ${{ inputs.session_start }}
          SESSION_END:   ${{ inputs.session_end }}
          DAY_ANCHOR:    ${{ inputs.day_anchor }}
          BASIS:         ${{ inputs.basis }}
          VALUE_TYPE:    ${{ inputs.value_type }}
        run: |
          set -euo pipefail
          echo "=== intraday snapshot (Astra4) ==="
          echo "INDEX_KEY=${INDEX_KEY}"
          echo "SESSION_START=${SESSION_START}"
          echo "SESSION_END=${SESSION_END}"
          echo "DAY_ANCHOR=${DAY_ANCHOR}"
          echo "BASIS=${BASIS}"
          echo "VALUE_TYPE=${VALUE_TYPE}"

          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-json "${OUT_JSON}" \
            --out-text "${OUT_TEXT}" \
            --snapshot-png "${SNAPSHOT_PNG}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --value-type "${VALUE_TYPE}"

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astra4_intraday_artifacts
          path: |
            docs/outputs/astra4_intraday.png
            docs/outputs/astra4_post_intraday.txt
            docs/outputs/astra4_stats.json
          if-no-files-found: ignore
          retention-days: 3

      - name: Commit outputs if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/outputs/astra4_intraday.png \
                  docs/outputs/astra4_post_intraday.txt \
                  docs/outputs/astra4_stats.json || true

          if ! git diff --cached --quiet; then
            git commit -m "chore(intraday): update astra4 (snapshot & post)"
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
            git push origin "HEAD:${BRANCH}"
          else
            echo "No output changes."
          fi
