name: Astra4 Intraday Snapshot

on:
  schedule:
    # 11:35 JST と 15:35 JST に自動実行
    - cron: '35 2 * * 1-5'  # 11:35 JST（= 02:35 UTC）
    - cron: '35 6 * * 1-5'  # 15:35 JST（= 06:35 UTC）
  workflow_dispatch:  # 手動実行も可
    inputs:
      reason:
        description: 'Manual trigger reason'
        required: false
        default: 'manual run'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify scripts & inputs exist
        run: |
          test -f scripts/make_intraday_post.py || (echo "Missing scripts/make_intraday_post.py" && exit 2)
          test -f docs/outputs/astra4_intraday.csv || (echo "Missing docs/outputs/astra4_intraday.csv" && exit 2)

      - name: Generate intraday post and snapshot
        env:
          INDEX_KEY: astra4
          CSV: docs/outputs/astra4_intraday.csv
          OUT_JSON: docs/outputs/astra4_stats.json
          OUT_TEXT: docs/outputs/astra4_post_intraday.txt
          SNAPSHOT_PNG: docs/outputs/astra4_intraday.png
          SESSION_START: "09:00"
          SESSION_END: "15:30"
          DAY_ANCHOR: "09:00"
          BASIS: prev_close
          VALUE_TYPE: ratio       # ← 値の種類を「比率」として明示
        run: |
          set -euo pipefail
          echo "=== intraday snapshot (Astra4) ==="
          echo "INDEX_KEY=${INDEX_KEY}"
          echo "SESSION_START=${SESSION_START}"
          echo "SESSION_END=${SESSION_END}"
          echo "DAY_ANCHOR=${DAY_ANCHOR}"
          echo "BASIS=${BASIS}"
          echo "VALUE_TYPE=${VALUE_TYPE}"

          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-json "${OUT_JSON}" \
            --out-text "${OUT_TEXT}" \
            --snapshot-png "${SNAPSHOT_PNG}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --value-type "${VALUE_TYPE}"

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astra4_intraday_outputs
          path: |
            docs/outputs/astra4_intraday.png
            docs/outputs/astra4_post_intraday.txt
            docs/outputs/astra4_stats.json

      - name: Commit outputs if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/outputs/astra4_intraday.png docs/outputs/astra4_post_intraday.txt docs/outputs/astra4_stats.json || true
          git diff --cached --quiet || git commit -m "chore(intraday): update astra4 (snapshot & post)"
          git push origin main
