name: ASTRA4 • intraday + publish (JST 09:00–15:30)

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  INDEX_KEY: ASTRA4
  LABEL: ASTRA4
  CSV: docs/outputs/astra4_intraday.csv
  DT_COL: Datetime
  BASIS: prev_close
  # 公開先サイト（←ここがtypoしがち）
  SITE_REPO: SakuraIndex/Sakura-Index-Site
  SITE_BRANCH: main
  PUBLISH_DIR: docs/charts/${{ env.INDEX_KEY }}
  OUT_JSON: docs/outputs/${{ env.INDEX_KEY, '' }}_stats.json
  OUT_TEXT: docs/outputs/${{ env.INDEX_KEY, '' }}_post_intraday.txt
  SNAPSHOT_PNG: docs/outputs/${{ env.INDEX_KEY, '' }}_intraday.png

concurrency:
  group: intraday-${{ github.ref }}-${{ env.INDEX_KEY }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # フォールバック用（最小）
          python - <<'PY'
          import sys,subprocess
          subprocess.check_call([sys.executable,"-m","pip","install","pandas","matplotlib"])
          PY

      - name: Verify inputs & files
        run: |
          set -e
          test -f "${CSV}" || (echo "Missing CSV: ${CSV}" && exit 1)
          test -f scripts/make_intraday_post.py || (echo "Missing script: scripts/make_intraday_post.py" && exit 1)

      - name: Decide publish variant (AM / PM)
        id: ampm
        shell: bash
        run: |
          H=$(TZ=Asia/Tokyo date +%H)
          if [ "$H" -lt 12 ]; then
            echo "variant=am" >> "$GITHUB_OUTPUT"
          else
            echo "variant=pm" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate intraday snapshot and post (with fallback)
        env:
          SESSION_START: '09:00'
          SESSION_END:   '15:30'
          DAY_ANCHOR:    '09:00'
          BASIS:         ${{ env.BASIS }}
          VALUE_TYPE:    percent
        run: |
          set -euo pipefail
          echo "=== Generate ${INDEX_KEY} intraday snapshot ==="
          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-json "${OUT_JSON}" \
            --out-text "${OUT_TEXT}" \
            --snapshot-png "${SNAPSHOT_PNG}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --dt-col "${DT_COL}" \
            --value-type "${VALUE_TYPE}" \
            --label "${LABEL}" || FALLBACK=1

          # フォールバック: PNG が無ければ超簡易チャートを作成
          if [ ! -f "${SNAPSHOT_PNG}" ]; then
            echo "[fallback] ${SNAPSHOT_PNG} を生成します"
            python - <<'PY'
            import pandas as pd, matplotlib.pyplot as plt, pathlib
            csv  = pathlib.Path("docs/outputs/astra4_intraday.csv")
            png  = pathlib.Path("docs/outputs/astra4_intraday.png")
            df   = pd.read_csv(csv)
            num  = [c for c in df.columns if c != "Datetime"]
            if len(num)==0:
              x=[0]; y=[0]
            else:
              y = df[num].mean(axis=1).tolist()
              x = range(len(y))
            plt.figure(figsize=(8,3), dpi=160)
            plt.plot(list(x), list(y))
            plt.title("ASTRA4 Intraday (fallback)")
            plt.tight_layout()
            png.parent.mkdir(parents=True, exist_ok=True)
            plt.savefig(png)
            PY
          fi

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astra4_intraday_artifacts
          path: |
            ${OUT_JSON}
            ${OUT_TEXT}
            ${SNAPSHOT_PNG}

      # —— ここからサイト反映 ——————————————————————————

      - name: Checkout site repo (for publishing)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SITE_REPO }}
          ref: ${{ env.SITE_BRANCH }}
          path: site
          token: ${{ secrets.SITE_PAT }}
          fetch-depth: 1

      - name: Copy snapshot files into site tree
        run: |
          set -e
          mkdir -p "site/${PUBLISH_DIR}"
          # 画像（1日チャート）
          cp -f "${SNAPSHOT_PNG}" "site/${PUBLISH_DIR}/astra4_1d.png"
          # stats.json（サイト側の loader が参照）
          cp -f "${OUT_JSON}"     "site/${PUBLISH_DIR}/astra4_stats.json"

      - name: Commit & push site charts
        working-directory: site
        run: |
          set -e
          git config user.name  "sakura-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No site changes."
          else
            git commit -m "chore(astra4): update charts & stats (snapshot & post)"
            git push origin "${{ env.SITE_BRANCH }}"
          fi
