name: Generate long-term charts (ASTRA4 7d/1m/1y)

on:
  workflow_dispatch:
  schedule:
    - cron: "25 1 * * *"   # 毎日 10:25 JST（append の後）

permissions:
  contents: write

concurrency:
  group: astra4-long-${{ github.ref }}
  cancel-in-progress: false

jobs:
  long:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      INDEX_KEY: astra4
      OUT_DIR: docs/outputs

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas matplotlib; fi

      - name: Render 7d/1m/1y charts (level)
        run: |
          python scripts/long_charts.py
          date -u +"%Y-%m-%dT%H:%M:%SZ" > "$OUT_DIR/_last_run.txt"
          ls -lah "$OUT_DIR" || true

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_DIR/${INDEX_KEY}_{7d,1m,1y}.png" "$OUT_DIR/_last_run.txt" 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(astra4): update long-term charts (7d/1m/1y)"
            git push
          fi
