name: ASTRA4 • intraday + publish (JST 09:00–15:30)

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  # ── Index/IO
  INDEX_KEY: ASTRA4
  LABEL: ASTRA4
  CSV: docs/outputs/astra4_intraday.csv
  OUT_JSON: docs/outputs/astra4_stats.json
  OUT_TEXT: docs/outputs/astra4_post_intraday.txt
  SNAPSHOT_PNG: docs/outputs/astra4_intraday.png
  DT_COL: Datetime
  BASIS: prev_close
  VALUE_TYPE_IN: percent
  # ── Session (JST)
  SESSION_START: "09:00"
  SESSION_END:   "15:30"
  DAY_ANCHOR:    "09:00"
  # ── Site repo
  SITE_REPO: Sakuralndex/Sakura-Index-Site
  SITE_BRANCH: main
  PUBLISH_DIR: charts/ASTRA4

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pandas matplotlib

      - name: Verify inputs & files
        run: |
          set -e
          test -f "${CSV}" || { echo "Missing CSV: ${CSV}"; exit 1; }
          test -f scripts/make_intraday_post.py || { echo "Missing script: scripts/make_intraday_post.py"; exit 1; }

      - name: Decide publish variant (AM / PM)
        id: ampm
        shell: bash
        run: |
          H=$(TZ=Asia/Tokyo date +%H)
          if [ "$H" -lt 12 ]; then
            echo "variant=am" >> "$GITHUB_OUTPUT"
          else
            echo "variant=pm" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate intraday snapshot and post (with fallback)
        shell: bash
        env:
          SESSION_START: ${{ env.SESSION_START }}
          SESSION_END:   ${{ env.SESSION_END }}
          DAY_ANCHOR:    ${{ env.DAY_ANCHOR }}
          BASIS:         ${{ env.BASIS }}
          VALUE_TYPE_IN: ${{ env.VALUE_TYPE_IN }}
        run: |
          set -euo pipefail
          echo "=== Generate ${INDEX_KEY} intraday snapshot ==="

          # ASTRA4 は --snapshot-png なしでも JSON/TEXT 出力に対応
          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-text "${OUT_TEXT}" \
            --out-json "${OUT_JSON}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --dt-col "${DT_COL}" \
            --value-type "${VALUE_TYPE_IN}"

          # PNG が無ければ簡易チャートをフォールバック生成（python -c で YAML 衝突回避）
          if [ ! -f "${SNAPSHOT_PNG}" ]; then
            echo "[fallback] ${SNAPSHOT_PNG} を生成します"
            python -c "import pandas as pd, matplotlib.pyplot as plt, pathlib; \
p=pathlib.Path('${CSV}'); q=pathlib.Path('${SNAPSHOT_PNG}'); \
df=pd.read_csv(p); cols=[c for c in df.columns if c!='${DT_COL}']; \
y=[0] if len(cols)==0 else df[cols].mean(axis=1).tolist(); \
plt.figure(figsize=(8,3), dpi=160); plt.plot(range(len(y)), y); \
plt.title('ASTRA4 Intraday (fallback)'); plt.tight_layout(); \
q.parent.mkdir(parents=True, exist_ok=True); plt.savefig(q)"
          fi

      - name: Upload artifacts (for debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astra4_intraday_artifacts
          path: |
            ${{ env.OUT_TEXT }}
            ${{ env.SNAPSHOT_PNG }}

      - name: Checkout site repo (for publishing)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SITE_REPO }}
          ref: ${{ env.SITE_BRANCH }}
          token: ${{ secrets.SITE_PAT }}
          path: site

      - name: Copy snapshot files into site tree
        shell: bash
        run: |
          set -e
          mkdir -p "site/${PUBLISH_DIR}"
          # intraday.png は存在すれば反映、無ければスキップ（このステップ以降は stats.json を使う想定）
          [ -f "${SNAPSHOT_PNG}" ] && cp -f "${SNAPSHOT_PNG}" "site/${PUBLISH_DIR}/intraday.png" || true
          cp -f "${OUT_JSON}" "site/${PUBLISH_DIR}/stats.json"

      - name: Commit & push site charts
        working-directory: site
        shell: bash
        run: |
          set -e
          git config user.name  "sakura-bot"
          git config user.email "bot@sakura-index.local"
          git add "${PUBLISH_DIR}/stats.json" || true
          [ -f "${PUBLISH_DIR}/intraday.png" ] && git add "${PUBLISH_DIR}/intraday.png" || true
          if git diff --cached --quiet; then
            echo "No site changes."
          else
            git commit -m "chore(ASTRA4): publish intraday snapshot & stats"
            git push origin "${{ env.SITE_BRANCH }}"
          fi
