name: ASTRA4 • intraday + publish (JST 09:00–15:30)

on:
  workflow_dispatch:
    inputs:
      session_start:
        description: "Session start (HH:MM JST)"
        required: true
        default: "09:00"
      session_end:
        description: "Session end (HH:MM JST)"
        required: true
        default: "15:30"
      day_anchor:
        description: "Day anchor time (HH:MM JST)"
        required: true
        default: "09:00"
      basis:
        description: "Return basis label"
        required: true
        default: "prev_close"
      value_type:
        description: "Value type: ratio | percent (override default)"
        required: false
        default: ""

  schedule:
    - cron: "35 2 * * 1-5"   # JST 11:35
    - cron: "35 6 * * 1-5"   # JST 15:35

permissions:
  contents: write

# ここは “固定値のみ” を定義（式は使わない）
env:
  INDEX_KEY: ASTRA4
  LABEL: ASTRA4
  CSV: docs/outputs/astra4_intraday.csv
  DT_COL: "Datetime"                 # 例: "Unnamed: 0" に合わせて変更可
  OUT_JSON: docs/outputs/astra4_stats.json
  OUT_TEXT: docs/outputs/astra4_post_intraday.txt
  SNAPSHOT_PNG: docs/outputs/astra4_intraday.png

  # 公開先サイト
  SITE_REPO: SakuraIndex/Sakura-Index-Site
  SITE_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    # ここで式を使って OK（env が参照可）
    concurrency:
      group: intraday-${{ github.ref }}-${{ env.INDEX_KEY }}
      cancel-in-progress: false

    # PUBLISH_DIR もジョブ側の env で、ここなら env が参照可
    env:
      PUBLISH_DIR: docs/charts/${{ env.INDEX_KEY }}

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify inputs & files
        run: |
          set -e
          test -f scripts/make_intraday_post.py || (echo "Missing scripts/make_intraday_post.py" && exit 1)
          test -f "${CSV}" || (echo "Missing CSV: ${CSV}" && exit 1)
          echo "OK: ${CSV}"

      - name: Generate intraday snapshot and post
        env:
          SESSION_START: ${{ inputs.session_start || '09:00' }}
          SESSION_END:   ${{ inputs.session_end   || '15:30' }}
          DAY_ANCHOR:    ${{ inputs.day_anchor    || '09:00' }}
          BASIS:         ${{ inputs.basis         || 'prev_close' }}
          VALUE_TYPE:    ${{ inputs.value_type    || '' }}
        run: |
          set -euo pipefail
          echo "=== Generate ${INDEX_KEY} intraday snapshot ==="
          python scripts/make_intraday_post.py \
            --index-key "${INDEX_KEY}" \
            --csv "${CSV}" \
            --out-json "${OUT_JSON}" \
            --out-text "${OUT_TEXT}" \
            --snapshot-png "${SNAPSHOT_PNG}" \
            --session-start "${SESSION_START}" \
            --session-end "${SESSION_END}" \
            --day-anchor "${DAY_ANCHOR}" \
            --basis "${BASIS}" \
            --value-type "${VALUE_TYPE}" \
            --dt-col "${DT_COL}" \
            --label "${LABEL}"

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astra4_intraday_artifacts
          path: |
            ${OUT_JSON}
            ${OUT_TEXT}
            ${SNAPSHOT_PNG}
          if-no-files-found: error
          retention-days: 3

      # サイトへ公開
      - name: Checkout site repo (for publishing)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SITE_REPO }}
          ref: ${{ env.SITE_BRANCH }}
          token: ${{ secrets.SITE_PAT }}
          path: site

      - name: Copy snapshot files into site tree
        run: |
          set -e
          mkdir -p "site/${PUBLISH_DIR}"
          cp -f "${SNAPSHOT_PNG}" "site/${PUBLISH_DIR}/intraday.png"
          cp -f "${OUT_TEXT}"     "site/${PUBLISH_DIR}/post_intraday.txt"
          cp -f "${OUT_JSON}"     "site/${PUBLISH_DIR}/stats.json"
          echo "Copied to site/${PUBLISH_DIR}"

      - name: Commit & push site charts
        working-directory: site
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${PUBLISH_DIR}/intraday.png" "${PUBLISH_DIR}/post_intraday.txt" "${PUBLISH_DIR}/stats.json" || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(charts): update ${INDEX_KEY} intraday"
            git push origin "${SITE_BRANCH}"
          else
            echo "No site changes."
          fi
