name: Generate long-term charts (Astra4)

on:
  workflow_dispatch:
  schedule:
    - cron: "25 6 * * *"  # JST 15:25頃 = 米国引け後の朝方に余裕を持って

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INDEX_KEY: astra4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytz matplotlib numpy
      - name: Generate long-term charts
        run: |
          python scripts/long_charts.py
      - name: Commit charts if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/* || true
          git commit -m "chore(charts): update Astra4 long-term charts" || echo "no changes"
          git push || true
