name: Daily Astra4 Snapshots

on:
  schedule:
    - cron: "0 0 * * 1-5"     # 平日 09:00 JST
    - cron: "30 2 * * 1-5"    # 平日 11:30 JST
    - cron: "30 6 * * 1-5"    # 平日 15:30 JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Astra4 snapshot
        run: python src/astra4_snapshot.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/* || true
          git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M')" || true
          git push || true
