name: Daily Astra4 Snapshots

permissions:
  contents: write

on:
  schedule:
    - cron: "35 6 * * *"   # 毎日 15:35 JST（= 06:35 UTC）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Astra4 snapshot
        run: python src/astra4_snapshot.py
      - name: Run Astra4 intraday (1-day)
        run: python src/astra4_intraday.py
      - name: Commit and push results
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/outputs/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto update: ASTRA4 outputs"
            git push
          else
            echo "No changes."
          fi
